### ISSUE TITLE
Fitness Function-Possible Improvements [Question]

### ISSUE THREAD

**Issue by abhishekms1047** [mishig25/neuroevolution-robots#1]
I was training the Humanoids . I observed that the humanoids were not motivated to cover longer distance in shorter time (Speed) because of fitness function . If fitness function includes SPEED as a motivator. Would the Humanoids learn to JUMP. Was this option tried? any suggestions on possibilities?

**Comment by mishig25** [comment]
Thats actually a great idea! That option was not tried. Feel free to test it and follow up with the results
